language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t namnguyendev/docker-react-github-travis-aws-beanstalk -f Dockerfile.dev .

script:
  - docker run -e CI=true namnguyendev/docker-react-github-travis-aws-beanstalk npm run test
