sudo: required
services:
  - docker

before_install:
  - docker build -t namnguyendev/docker-react-github-travis-aws-beanstalk -f Dockerfile.dev .

script:
  - docker run namnguyendev/docker-react-github-travis-aws-beanstalk npm run test -- --coverage
